### ISSUE TITLE
errors when connecting to geoserver CSW service

### ISSUE THREAD

**Issue by yan073** [AuScope/portal-core#334]
I added one GeoTiff data source as a store in Geoserver 2.13.0.
Then, I added the serviceUrl into the vl-registries.xml in the anvgl-portal project. 
When running the anvgl-portal in tomcat, portal-core prepared and sent csw-GetRecords request to GeoServer. Geoserver replied with error message, complaining wrong parameters in the GetRecords request:

1. org.auscope.portal.core.services.responses.ows.OWSException: Code='InvalidParameterValue' Message='Illegal namespace declaration, should be of the form xmlns(<prefix>=<ns uri>): csw:http://www.opengis.net/cat/csw'
	at org.auscope.portal.core.services.responses.ows.OWSExceptionParser.checkForExceptionResponse(OWSExceptionParser.java:109)
	at org.auscope.portal.core.services.CSWService.queryCSWEndpoint(CSWService.java:124)

2. org.auscope.portal.core.services.responses.ows.OWSException: Code='InvalidParameterValue' Message='Cannot encode records in output schema csw:IsoRecord'
	at org.auscope.portal.core.services.responses.ows.OWSExceptionParser.checkForExceptionResponse(OWSExceptionParser.java:109)
	at org.auscope.portal.core.services.CSWService.queryCSWEndpoint(CSWService.java:124)
	at org.auscope.portal.core.services.CSWService.queryCSWEndpoint(CSWService.java:75)
	at org.auscope.portal.core.services.CSWCacheService$CSWCacheUpdateThread.run(CSWCacheService.java:657)

After fixing these two errors, geoserver could not find the created data source in the catalogue.

**Comment by vjf** [comment]
This has been fixed.
